version: "3.1"

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      # - ./docker-compose/nginx:/etc/nginx/conf.d

volumes:
  webserverdata:
    driver: local
