version: "3"
volumes:
  rethindb-data:
    external: true
services:
  db:
    image: rethinkdb:latest
    ports:
      - "8080:8080"
      - "29015:29015"
      - "28015:28015"
  # api:
  #   image: hello-nodemon
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=80
  #     - DB_HOST=localhost
  #     - DB_PORT=28015
  #   deploy:
  #     # replicas: 5
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 50M
  #     restart_policy:
  #       condition: on-failure
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - .:/src/jv-agricultor
  #     - /src/jv-agricultor/node_modules
  #   depends_on:
  #     - db
  #   networks:
  #     - webnet
networks:
  webnet: